name: capapp
description: CAP App - Mobile and Web app for Android and Web.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  intl: ^0.20.2
  image_picker: ^1.0.0
  permission_handler: ^12.0.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  file_picker: ^10.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
